version: '3'
services:
  flask-backend:
    build: 
      context: .
      dockerfile: Dockerfile-flask
    ports:
      - "5001:5001"
  
  streamlit-frontend:
    build: 
      context: .
      dockerfile: Dockerfile-streamlit
    ports:
      - "8501:8501"
    depends_on:
      - flask-backend