name: Docker Build and Push

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image (Flask)
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        file: ./backend/Dockerfile-flask
        push: true
        tags: ghcr.io/${{ github.repository }}/flask-backend:latest

    - name: Build and Push Docker Image (Streamlit)
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        file: ./frontend/Dockerfile-streamlit
        push: true
        tags: ghcr.io/${{ github.repository }}/streamlit-frontend:latest
